[package]
name = "netcode_game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.14"
miniquad = "0.4.8"
image = "0.25.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
bincode = "1.3"
minifb = "0.28.0"
rand = "0.9.1"