[package]
name = "netcode_game"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
bincode = "1.3"
minifb = "0.28.0"
tokio = { version = "1", features = ["full"] }