name: Build, Test, Docs, Coverage

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.87.0
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --all-targets --verbose

  docs-and-coverage:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.87.0
          override: true

      - name: Install cargo-llvm-cov and llvm-tools-preview
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov

      - name: Generate Coverage Report
        run: cargo llvm-cov --all-features --workspace --html

      - name: Generate Docs
        run: cargo doc --no-deps --verbose

      - name: Copy README into docs
        run: cp README.md target/doc/

      - name: Copy coverage report into docs
        run: cp -r target/llvm-cov/html target/doc/coverage

      - name: Create index.html to redirect to crate docs
        run: |
          CRATE_NAME=$(basename $(pwd))
          echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_NAME}/index.html\">" > target/doc/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: gh-pages
